# require: rubocop-rspec

# Max line length is changed from default 80
Metrics/LineLength:
  Max: 100

# Max class definition is changed from default 100
Metrics/ClassLength:
  Max: 150

# Class top level documentation
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# assignment branch condition size
Metrics/AbcSize:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'
    - 'test/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/seeds/**/*'
    - 'bin/**/*'
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
    - 'config/routes.rb'
